#!/usr/bin/env bash
#find files
i=school
if [ -e $i ]; then
	echo "School file exists"
		if [ -s $i ]; then
			echo "School file is not empty"
		else
			echo "School file is empty"
		fi
			if [ -f $i ]; then
				echo "School is a regular file"
			fi
else
	echo "School file does not exist"
fi
